options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PROJECT : "api-project-119360632367"
  _REGION : "us-east1"
  _APP_IMAGE : "ubuntu"
  _DEPLOYMENT : "projects/${_PROJECT}/locations/${_REGION}/deployments/qa"
  _DOCKER_IMAGE : "us-east1-docker.pkg.dev/${_PROJECT}/calendar/main"
  _SERVICE : "calendar"
  _GITHUB_REPOSITORY : "https://github.com/t-hale/calendar"
  _GITHUB_SOURCE_DIRECTORY : 'terraform'
  _GITHUB_SOURCE_REF : 'master'
  _SERVICE_ACCOUNT : "projects/${_PROJECT}/serviceAccounts/infrastructure@${_PROJECT}.iam.gserviceaccount.com"
steps:
  - id: "Deploy cloud infrastructure"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - './scripts/deploy_infra.sh'
      - '--deployment'
      - '$_DEPLOYMENT'
      - '--service_account'
      - '$_SERVICE_ACCOUNT'
      - '--github_repo'
      - '$_GITHUB_REPOSITORY'
      - '--git_source_directory'
      - '$_GITHUB_SOURCE_DIRECTORY'
      - '--git_source_ref'
      - '$_GITHUB_SOURCE_REF'

