options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PROJECT : "api-project-119360632367"
  _REGION : "us-east1"
  _APP_IMAGE : "ubuntu"
  _SERVICE : "calendar"
  _DEPLOYMENT : "qa"
  _GITHUB_REPO : "https://github.com/t-hale/family-cal"
  _SERVICE_ACCOUNT : "infrastructure@api-project-119360632367.iam.gserviceaccount.com"
steps:
  - id: "Deploy cloud infrastructure"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: "gcloud"
    args:
      - 'infra-manager'
      - 'deployments'
      - 'apply'
      - 'projects/$_PROJECT/locations/$_REGION/deployments/$_DEPLOYMENT'
      - '--service-account=projects/$_PROJECT/serviceAccounts/$_SERVICE_ACCOUNT'
      - '--git-source-repo=$_GITHUB_REPO'
      - '--git-source-directory=terraform'
      - '--git-source-ref=master'