options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DOCKER_IMAGE: 'us-east1-docker.pkg.dev/api-project-119360632367/calendar/main'
steps:
  # Step 1: Compile Golang protobufs
  - id: 'Compile Golang protobufs'
    name: 'namely/protoc-all'
    entrypoint: 'bash'
    args: [ './scripts/build_proto.sh' ]

  # Step 2: Build and push the Docker image
  - id: 'Build and push docker image'
    name: 'ubuntu'
    entrypoint: 'bash'
    args: [ './scripts/build_and_push_docker.sh' ]

