options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DOCKER_IMAGE: 'us-east1-docker.pkg.dev/api-project-119360632367/calendar/main'
steps:
  # Step 1: Build the Docker image
  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_DOCKER_IMAGE}'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - id: 'Push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_DOCKER_IMAGE}'

  # Step 3: Publish a message to the push-image GCP Pub/Sub topic
  - id: 'Publish to Pub/Sub'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'push-image'
      - '--message'
      - 'Image pushed: ${_DOCKER_IMAGE}'