options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DOCKER_IMAGE: 'us-east1-docker.pkg.dev/api-project-119360632367/calendar/main'
steps:
  # Step 1: Build the Docker image
  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_DOCKER_IMAGE}'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - id: 'Push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_DOCKER_IMAGE}'
